version: "3.6"
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "xpense"
    volumes:
      - "xpense_postgresql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  xpense_postgresql:
    external: true
