version: "3.6"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    volumes:
      - "xpense_postgresql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - fullstack

volumes:
  api:
  xpense_postgresql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
